### ISSUE TITLE
node.ks should never burn unless facing is correct

### ISSUE THREAD

**Issue by xeger** [xeger/kos-ramp#10]
@fellipec said:
> Anyway if the node is too soon and ship is turned completely away from its direction, it will miss the begining of burn window. Before it even start to burn to the wrong direction, I added the code just before the wait 5 so the script at least wait the ship to turn facing more or less in the direction of the burn. I think is “less worse” than begin burning in the wrong direction.

Our `node` program _begins_ by facing the burn, and it does not proceed until we're facing correctly (less than 0.5 degrees of combined error):
https://github.com/xeger/kos-ramp/blob/master/node.ks#L33

However, the `WAIT` loop has another exit condition: it will proceed if we are about to miss our burn window, even if we aren't facing correctly. The rationale is:
1. precise timing is critical for some burns (e.g. interplanetary) but delta-v errors can be corrected mid course
2. most engines have gimbals; for a large vessel with poor control authority, beginning the burn usually _helps_ steer the vessel toward the burn.

The problem that @fellipec pointed out, is that the mission script does not perform any mid-course corrections! Automated correction would be difficult, but without having it, the current logic can cause an automated mission to fail badly.

Also, it's a valid argument that a vessel _should_ have good enough stability and control authority to face its burn without engine power.

I'll show my proposal for fixing both of these issues.

**Comment by fellipec** [comment]
@xeger Agree that is important to don't miss the burn window and that engine gimbals should help the ship steer to the right side.

I added that check because in my KSP experience often I fly shuttles that even with RCS and reasonable reaction wheels take about 20~30 seconds to turn 180º. (Not that bad!) and doing minor burns (Raising periapsis, adjusting inclination, etc) where there is little deltaV involved, usually burns in the wrong direction do more harm than waiting for the ship turn, at least, in the general direction fo the burn. That is the reason that my check goes for a 40º error. But a more elegant solution for this will be very welcome.

**Comment by xeger** [comment]
I think your initial solution is good enough to allow for engine gimbaling. I had one additional suggestion, which is to cut thrust _during_ the burn if we go too far off course for some reason. It's a good emergency safeguard, but like your before-burn solution, allows for gimbal thrust.

Perform some maneuvers with your shuttle using the code in #11 and let me know if it helps (or hurts) burn stability.

**Comment by xeger** [comment]
The ideal solution would probably use dv as a guide for selecting the precision; in any case, this is a big improvement. Thanks for the contribution!
